# Generated by Django 5.2.14 on 2026-05-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Queue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('token_number', models.IntegerField()),
                ('status', models.CharField(default='WAITING', max_length=20)),
            ],
        ),
    ]
